version: '3.8'

services:
  db:
    image: postgres:15-alpine
    hostname: db
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docky_share
    volumes:
      - /var/lib/postgresql/data-docky:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "3001"
    environment:
      NODE_ENV: production
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    ports:
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  redis_data:
  nginx_logs:
